### ISSUE TITLE
create targetOrganism dictionary

### ISSUE THREAD

**Issue by petermr** [petermr/CEVOpen#21]
Many articles have tests against specific species or genera. Examples
* bacteria
* viruses
* fungi
* worms (esp. parasitic)
* parasites (e.g. malaria)
* vectors (e.g. Aedes mosquito)

Ambarish has made a start by extracting about 50 target organisms, from a small number of articles

[targetOrganism](./dictionary/TargetOrganism.xml)

we should move this into its own dictionary

**Comment by ambarishK** [comment]
Sir, check for the dictionary file for target organisms - 
[targetOrganism.xml](https://github.com/petermr/CEVOpen/blob/master/dictionary/targetOrganism/targetOrganismNew.xml)

[targetOrganism.csv](https://github.com/petermr/CEVOpen/blob/master/dictionary/targetOrganism/raw/TargetOrganismNew.csv)
