### ISSUE TITLE
Ocimum sanctum - Literature survey - An example of Text and Data mining.

### ISSUE THREAD

**Issue by ambarishK** [petermr/CEVOpen#23]
Sir, Please go through the sheet for literature survey over `Ocimum sanctum`. It covers 150 articles of `ocimum200` corpus.

It is in raw state and I will modify it for two to three times.

It will produce reported `activity`, `diseases`,` target organisms (as species)`,`plant species used as synergistic action`, `chemical compounds ( along with their activity)`, `study domain ( genomics, agronomy/farming, nano-science)`, `miscellaneous uses` as well as `social and cultural aspects` over ocimum sanctum.

[Ocimum sanctum raw sheet](https://github.com/petermr/CEVOpen/blob/master/dictionary/plant/raw/ocimumSanctum.tsv).

We can extract correlation between reported chemical compounds with diseases, activities, target organisms (pathogens/insects/microbes), related plant species (for similar/related and synergistic action). 

I am modifying it right now.

I have shared the raw spread-sheet (over Google Sheets).

Also, it present useful statistics related Ocimum sanctum research and usefulness.

**Comment by petermr** [comment]
Not directly relevant to CEV strategy
