### ISSUE TITLE
Normalization of Chemical Compound Names

### ISSUE THREAD

**Issue by mannyrules** [petermr/CEVOpen#66]
Issues to consider when normalizing chemical compound names

**Comment by petermr** [comment]
You should put more details into Issues. You have assigned me a task but I have no idea what to do. 
I also expect that this issue could be included in some of the open issues

**Comment by mannyrules** [comment]
Looking at [compound_multiset.tsv](https://github.com/petermr/CEVOpen/blob/master/searches/oil1000/__tables/compound_multiset.tsv), I found a couple of things to make decisions on regarding normalization:

**1. See column 3 (WIKIDATA_query) for lines 4 (Limonene) and 5 (linolool): Do we normailze to **+/-** or **±**** 
_(Out of curiosity,  do we prefer what we expect users might type into a search field, or what takes fewer characters? Or Is the latter (±) a "special character" that may not display or search properly on some machines or systems)?_

**2. Line 7 column 3 = 	Î³-terpinene  ... (should be gamma, I think)**
_Question: If this is not a typo, but a potential recurring problem resulting from the use of a "special character?" do we add this as sort of a false synonym?_

**3. also look at line 33 to replace gamma in (+)-γ-cadinene**

**4. Line 22: 	(-)-α-phellandrene  .... I believe we're spelling out greek characters, such as alpha. There are many more to find and replace**

**5. At the end of each pull, automatically find and replace "-(space)" [lines 402, 552, 353]  and "(space-)" [none found in this set] with "-" no space**

**Comment by mannyrules** [comment]
> You should put more details into Issues. You have assigned me a task but I have no idea what to do.
> I also expect that this issue could be included in some of the open issues

Done. Please re-open issue if corrected to your satisfaction.
