### ISSUE TITLE
❓   QUESTIONS for Gita

### ISSUE THREAD

**Issue by mannyrules** [petermr/CEVOpen#7]
### We've got questions, Gita's got answers!

**Comment by mannyrules** [comment]
When looking at a value of a compound derived from Gas Chromatography, can we be sure at the specific "chiral type" of the compound? To be certain does the method need to be listed as Chiral Gas Chromatography?

**Comment by gilienv** [comment]
Chirality cannot be derived from regular GC experiments. Most of the data we have in EssoilDB is non chiral GC.

**Comment by petermr** [comment]
That's what I assumed. So how do they "know" the chirality when they report the profile. Just guess it's the commonest or only isomer?

**Comment by gilienv** [comment]
I meant that most profile datasets do not have chirality information. 

However, it is possible “in some cases” to separate/ identify the enantiomers of a given compound.    They use a special filter in the GC for this and in such cases, the Methodology section of the paper would mention that its chiral GC. Even so, we may never get enantiomers for each compound in the profile.
