### ISSUE TITLE
normalize country names for plant origins against Wikidata

### ISSUE THREAD

**Issue by petermr** [petermr/CEVOpen#72]
@ambarishK 
Please collect all sections which mention where plants/oils originated (titles usually like "Origin of plant material").

Build a new TSV file which records 
* name of section containing plant or oil origin
* country/countries mentioned in this section specifying where oil came from
* look up country in Wikidata

**Comment by ambarishK** [comment]
OK sir.

**Comment by ambarishK** [comment]
Sir, please review the extraction sheet for plant material location - [country20191222.tsv](https://github.com/petermr/CEVOpen/blob/master/articleAnalysis/oil186/raw/country20191222.tsv).

There are records extracted from first '30' articles of 'oil186'.

**Comment by petermr** [comment]
Looks a useful start

**Comment by ambarishK** [comment]
Sir, please review the complete extraction of plant material location extraction sheet - [country20191222.tsv](https://github.com/petermr/CEVOpen/blob/master/articleAnalysis/oil186/raw/country20191222.tsv)

There are 138 articles which mention plant material location.

Two articles which mentions multiple locations for plant material.

```
PMC5830750   	Material   	France      	Q142
PMC5830750   	Material   	Ireland     	Q27
PMC5830750   	Material   	Serbia      	Q403
PMC5717781   	Material   	Iran          	Q794
PMC5717781   	Material   	India         	Q668
PMC5717781   	Material   	China       	Q29520

```

There are 48 articles which either does not mention plant material location or not related with plant EO.
