### ISSUE TITLE
Requesting help with Uniprot SPARQL Query to retrieve Synonyms, Protein names 

### ISSUE THREAD

**Issue by sasujadhav1** [petermr/CEVOpen#95]
Hi, I request you help with my SPARQL query troubleshooting.

Please find xml file for one of Uniprot ID.

https://www.uniprot.org/uniprot/A0A2I0B0T8.xml

I have uniprot IDs and want to retreive  
Full name,
EC NUMBER,
Protein ID
Organism Scientific name

https://sparql.uniprot.org/
https://www.uniprot.org/docs/uniprot.xsd
https://ftp.uniprot.org/pub/databases/uniprot/current_release/rdf/

Thank you.

**Comment by petermr** [comment]
I am not quite clear what you are trying to do:
* https://sparql.uniprot.org/
 This is the SPARQL endpoint. It expects queries to be based on an RDF model
 
* https://www.uniprot.org/docs/uniprot.xsd
 This is the Uniprot XML schema which describes the structure of a Uniprot XML file
* https://www.uniprot.org/uniprot/A0A2I0B0T8.xml
 This is an example of a Uniprot XML file
 
 We would need to know:
 * which fields of the XML file you want to extract.
 * how they are represented in RDF
 
 I suspect the best thing is to find a tutorial.

**Comment by sasujadhav1** [comment]
I solved above query by following protocol:
I mapped uniprotkb/ac id to uniprot kb. Then changed the column settings by adding required fields. Then downloaded excel file.
